{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "7dfe25df_f1fa26f0",
        "filename": "vpd-tool/src/vpd_tool.cpp",
        "patchSetId": 1
      },
      "lineNbr": 288,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2025-01-23T14:05:53Z",
      "side": 1,
      "message": "This is required for the output format?",
      "revId": "864615864d5bd90ae19eb13490d33ee3c2bb4bf6",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "184bbb25_d9366dc5",
        "filename": "vpd-tool/src/vpd_tool.cpp",
        "patchSetId": 1
      },
      "lineNbr": 990,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2025-01-23T14:05:53Z",
      "side": 1,
      "message": "A bit confused here. In the for loop if a mismatch is fond then we set \"l_anyMismatchFound \u003d true\"\n\nAfter that let\u0027s say \"writeKeyword\" fails and code goes to exception. Then you log error to console and then come here and log that data updated successfully.\n\nIs that by design?",
      "revId": "864615864d5bd90ae19eb13490d33ee3c2bb4bf6",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}