{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "83c27d1d_fdf2de18",
        "filename": "vpd-manager/src/logger.cpp",
        "patchSetId": 33
      },
      "lineNbr": 252,
      "author": {
        "id": 1001932
      },
      "writtenOn": "2025-10-22T09:03:36Z",
      "side": 1,
      "message": "in case of error, we quietly returning from the API, caller is continuing writing to existing file. should we handle this scenario ?",
      "revId": "8f95c7df07381f7e522afa1475c5dece9809686f",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "235d21a1_acd1064b",
        "filename": "vpd-manager/src/logger.cpp",
        "patchSetId": 33
      },
      "lineNbr": 299,
      "author": {
        "id": 1001932
      },
      "writtenOn": "2025-10-22T09:03:36Z",
      "side": 1,
      "message": "In case of failure, we continue open and write to old file(which exceeds max lines). Is this expected behaviour ?",
      "revId": "8f95c7df07381f7e522afa1475c5dece9809686f",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}