{
  "comments": [
    {
      "key": {
        "uuid": "fb55162f_020577ef",
        "filename": "ibm_vpd_app.cpp",
        "patchSetId": 5
      },
      "lineNbr": 1051,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2021-04-21T06:01:26Z",
      "side": 1,
      "message": "Why we need this here? We are again throwing the exception which will be caught at line 1084 and will output the what().",
      "revId": "a683a8a5225215dbe3a8873a0382d74d7e0cd3c8",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4",
      "unresolved": true
    }
  ]
}